# Generated by Django 5.2.5 on 2025-10-02 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naleh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='producs/')),
            ],
        ),
    ]
