# Generated by Django 5.2.5 on 2025-10-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naleh', '0002_newproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='newproducts',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='newproducts',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
